#%RAML 1.0 Library
types:
  customers:
    type: array
    items: customer
  customer:
    type: object
    properties:
      name: string
      address?: string
      phone?: string
      email: string